feed-master2:
    image: umputun/feed-master:master
    container_name: feed-master2
    hostname: feed-master2
    restart: always

    environment:
        - MHOST
        - DEBUG=false
        - FM_DB=/srv/var/feed-master.bdb
        - FM_CONF=/srv/etc/fm.yml
    volumes:
        - ./etc:/srv/etc
        - ./var:/srv/var
        - ./static:/srv/static
    ports:
        - "8097:8080"
