version: "2"

services:
    feed-master:
        build: .
        image: umputun/feed-master:master
        container_name: feed-master
        hostname: feed-master
        restart: always

        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

        environment:
            - MHOST
            - DEBUG=false
            - FM_DB=/srv/var/feed-master.bdb
            - FM_CONF=/srv/etc/fm.yml
        volumes:
            - ./var:/srv/var # mapped location to save status
            - ./_example/etc:/srv/etc # mapped location for config
            - ./_example/static:/srv/static # mapped location for images
        ports:
            - "8097:8080"
